In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
import tensorflow as tf
import array as arr
import numpy as np
import scipy.io as sio
import matplotlib.pyplot as plt
%matplotlib inline

In [0]:
def y_data_mat(list_path, info):
    mat_file = sio.loadmat(list_path)
    y_name_array = mat_file[info][0][0][0]
    y_train = []
    category_dict = dict()
    with open("/content/drive/My Drive/Colab Notebooks/map.txt", 'r') as infile:
        for line in infile:
            line = line.strip().split()
            category_dict[line[0]] = line[1] 
    for i in range(len(y_name_array)):
        name = y_name_array[i][0][0].split("/")[0].split("-",1)[1]
        category_index = category_dict[name]
        y_train.append(int(category_index))
    y_train = np.array(y_train)
    return y_train

In [0]:
# y_data_mat("/content/drive/My Drive/Colab Notebooks/train_data.mat")


In [0]:
def x_data_mat(list_path,type):
    mat_file = sio.loadmat(list_path)
    a = sorted(mat_file.keys())
    array = mat_file[type]
    return array

In [0]:
# x_data_mat("/content/drive/My Drive/Colab Notebooks/train_data.mat", 'train_data')

In [0]:
x_train = x_data_mat("/content/drive/My Drive/Colab Notebooks/train_data.mat", 'train_data')
x_test = x_data_mat("/content/drive/My Drive/Colab Notebooks/test_data.mat", 'test_data')
y_train = y_data_mat("/content/drive/My Drive/Colab Notebooks/train_data.mat", 'train_info')
y_test = y_data_mat("/content/drive/My Drive/Colab Notebooks/test_data.mat", 'test_info')

In [0]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(512, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(120)
])

In [11]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.25692105,  0.49219444, -0.36371273, -0.24882458,  0.24772997,
         0.12330627, -0.19337918, -0.6120679 , -0.49509263, -0.13737626,
        -0.2940473 ,  0.01445938, -0.3735778 ,  0.72020614,  0.10265759,
         0.12365677, -0.09515376,  0.33902657, -0.6594857 ,  0.68341804,
         0.5225028 , -0.1942741 , -0.4709517 , -0.8154605 , -0.27993047,
         0.5062284 , -0.23822598, -1.1045389 ,  0.7988022 ,  0.17605948,
         0.8924733 , -0.34215802, -0.63335186, -0.23933263,  0.1873253 ,
        -0.47341743,  0.01820301, -0.5015633 ,  0.09253702,  0.11119975,
         0.04603972, -0.17280728, -0.69125515, -0.12195138,  0.04345483,
         0.8829461 ,  0.22050583,  0.1307347 ,  0.2243262 , -0.06951192,
        -0.1808402 ,  0.5954784 ,  0.2883836 , -0.22370932,  0.22697058,
         0.45431814, -0.00591904, -0.8535755 ,  0.604406  , -0.31377876,
        -0.24052405, -0.16636753, -0.44499388,  0.2466689 , -0.3364392 ,
        -0.251566  ,  0.7754529 ,  1.034027  , -0.3

In [14]:
tf.nn.softmax(predictions).numpy()

array([[0.00581024, 0.0122894 , 0.00522174, 0.00585747, 0.00962412,
        0.00849815, 0.00619141, 0.00407339, 0.00457886, 0.00654804,
        0.00559848, 0.00762172, 0.00517048, 0.01543672, 0.00832448,
        0.00850113, 0.00683044, 0.01054413, 0.00388474, 0.01487915,
        0.01266757, 0.00618588, 0.00469074, 0.00332371, 0.00567808,
        0.01246309, 0.00591988, 0.00248931, 0.01669894, 0.0089585 ,
        0.01833875, 0.00533551, 0.00398761, 0.00591334, 0.00905999,
        0.00467919, 0.00765031, 0.00454933, 0.00824066, 0.00839589,
        0.00786626, 0.0063201 , 0.00376327, 0.00664983, 0.00784595,
        0.01816486, 0.00936565, 0.00856152, 0.0094015 , 0.00700785,
        0.00626954, 0.01362656, 0.01002344, 0.00600645, 0.00942639,
        0.01183263, 0.00746797, 0.00319941, 0.01374876, 0.0054891 ,
        0.0059063 , 0.00636093, 0.0048141 , 0.00961392, 0.00536611,
        0.00584144, 0.01631354, 0.02112738, 0.00525058, 0.00799979,
        0.00956712, 0.01350827, 0.00767881, 0.00

In [0]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [17]:
loss_fn(y_train[:1], predictions).numpy()

4.11576

In [1]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

NameError: name 'model' is not defined

In [2]:
model.fit(x_train, y_train, epochs=5)

NameError: name 'model' is not defined

In [0]:
2

In [0]:
from tensorflow.keras.utils import to_categorical

In [0]:
y_cat_train = to_categorical(y_train)
y_cat_test = to_categorical(y_test)

In [0]:
# x_train = x_train.reshape(12000,12000,1)
# x_test = x_test.reshape(8580,12000,1)

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Conv2D, MaxPool2D, Flatten

from tensorflow.keras.callbacks import EarlyStopping

In [0]:
model = tf.keras.models.Sequential([
  # tf.keras.layers.Flatten(input_shape=(12000, 1)),
  tf.keras.layers.Dense(256, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(120)
])

In [0]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [0]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [0]:
y_train.shape
x_train.shape

(12000, 12000)

In [0]:
model.fit(x_train, y_train, epochs=1)

375/375 [==============================] - 8s 21ms/step - loss: 4.8333 - accuracy: 0.0063


In [0]:
model.evaluate(x_test,  y_test, verbose=2)

269/269 - 2s - loss: 4.7876 - accuracy: 0.0061


[4.787626266479492, 0.0060606058686971664]

In [0]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [0]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 120), dtype=float32, numpy=
array([[0.00831052, 0.00838217, 0.00833976, 0.00831697, 0.00828434,
        0.00832154, 0.00830068, 0.00839559, 0.00836179, 0.00830673,
        0.00832102, 0.00836506, 0.00834128, 0.00832635, 0.00829916,
        0.00832826, 0.00831164, 0.0083556 , 0.0083342 , 0.00833145,
        0.00834986, 0.00833571, 0.00832466, 0.00833711, 0.00837951,
        0.00831635, 0.00834108, 0.00831843, 0.00831177, 0.0083491 ,
        0.00833282, 0.00833461, 0.00832813, 0.00834335, 0.00834553,
        0.00832312, 0.0083129 , 0.00831673, 0.00832912, 0.00833654,
        0.00829391, 0.00833713, 0.00832766, 0.00833022, 0.00833384,
        0.00834641, 0.00836087, 0.00827279, 0.00832125, 0.00830583,
        0.00832467, 0.0083431 , 0.00833433, 0.0082759 , 0.00830886,
        0.00834378, 0.00835085, 0.00831947, 0.00830491, 0.00832714,
        0.00832756, 0.00832269, 0.0083432 , 0.00833541, 0.0083613 ,
        0.00832328, 0.00832952, 0.00835964, 0.00833909, 0.00835258